### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by nncl** [DiegoSestito/ngx-cpf-cnpj#1]
Hello.

I'm getting the following error when adding into my app's module:

```
ERROR in node_modules/ngx-cpf-cnpj/lib/cpf-cnpj-validator.directive.d.ts(6,37): error TS1144: '{' or ';' expected.
node_modules/ngx-cpf-cnpj/lib/cpf-cnpj-validator.directive.d.ts(7,23): error TS1005: ';' expected.
node_modules/ngx-cpf-cnpj/lib/cpf-cnpj-validator.directive.d.ts(8,1): error TS1128: Declaration or statement expected.
```

**Comment by DiegoSestito** [comment]
Hello, can you give me more info about your project? What is the angular version? How are you doing the import?

**Comment by nncl** [comment]
Hi, thanks for the quick response.

The project I've tested for the first time used Angular 6, and the way I'd imported was exactly the same as you described on `readme.md` file.

However, I just tested on a fresh angular 7 project and worked like a charm. I'm so sorry burning your time.

Thanks for your patience.
