### ISSUE TITLE
Error applying mask

### ISSUE THREAD

**Issue by nncl** [DiegoSestito/ngx-cpf-cnpj#2]
Hi.

When I type this following CNPJ `25405022000162` the mask shows `2.540.502/2000-162` instead of `25.405.022/0001-62`.

I've tested with others and the same is happening. It doesn't happens if I copy it correctly and paste on the input.

**Comment by mrmgomes** [comment]
Indeed the mask is wrong. Is this going to be fixed ?

**Comment by DiegoSestito** [comment]
Yes, I'll fix this problem later this week.

**Comment by laioviana** [comment]
Having the same error here.

**Comment by DiegoSestito** [comment]
This issue has been corrected in version 1.0.4
